services:
  - type: web
    name: sona-play-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: COOKIE_FILE
        sync: false
      - key: PROXY_URL
        sync: false
